import { fallbackVideos } from "../../shared/fallbackVideos";
import type { ApiRequest, ApiResponse } from "../_lib/http";
import { sendError } from "../_lib/http";
type VideoRow={id:string;title:string;thumbnail:string;publishedAt:string;durationSeconds:number;isShort:boolean;url:string};
function duration(value:string):number{const m=value.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);return m?Number(m[1]??0)*3600+Number(m[2]??0)*60+Number(m[3]??0):0;}
function isVideoRow(value:unknown):value is VideoRow{return typeof value==="object"&&value!==null&&"id" in value&&"url" in value;}
async function rss(channelId:string):Promise<VideoRow[]>{const response=await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(channelId)}`,{headers:{accept:"application/atom+xml"},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error("YouTube feed unavailable");const xml=await response.text();const rows=[...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)];return rows.slice(0,20).flatMap((match)=>{const text=match[1]??"";const id=text.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1];const title=text.match(/<title>([^<]+)<\/title>/)?.[1];const publishedAt=text.match(/<published>([^<]+)<\/published>/)?.[1];if(!id||!title)return[];const decoded=title.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"');return[{id,title:decoded,thumbnail:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,publishedAt:publishedAt??new Date(0).toISOString(),durationSeconds:0,isShort:false,url:`https://www.youtube.com/watch?v=${id}`}];});}
export default async function handler(req:ApiRequest,res:ApiResponse):Promise<void>{if(req.method!=="GET"){sendError(res,405,"METHOD_NOT_ALLOWED","Method not allowed.");return;}res.setHeader("Cache-Control","s-maxage=3600, stale-while-revalidate=86400");const key=process.env.YOUTUBE_API_KEY;const channelId=process.env.YOUTUBE_CHANNEL_ID;try{if(key&&channelId){const channelResponse=await fetch(`https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=${encodeURIComponent(channelId)}&key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout(6000)});if(!channelResponse.ok)throw new Error("YouTube API unavailable");const channelData=await channelResponse.json() as {items?:Array<{contentDetails?:{relatedPlaylists?:{uploads?:string}}}>};const uploads=channelData.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;if(!uploads)throw new Error("Uploads playlist missing");const itemsResponse=await fetch(`https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=${encodeURIComponent(uploads)}&key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout(6000)});if(!itemsResponse.ok)throw new Error("Uploads request failed");const itemData=await itemsResponse.json() as {items?:Array<{snippet?:{title?:string;publishedAt?:string;resourceId?:{videoId?:string}}}>};const entries=itemData.items?.flatMap(item=>{const id=item.snippet?.resourceId?.videoId;return id?[{id,title:item.snippet?.title??"ShuzhFit video",publishedAt:item.snippet?.publishedAt??new Date(0).toISOString()}]:[]})??[];if(entries.length){const ids=entries.map(x=>x.id).join(",");const detailsResponse=await fetch(`https://www.googleapis.com/youtube/v3/videos?part=contentDetails&id=${encodeURIComponent(ids)}&key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout(6000)});if(!detailsResponse.ok)throw new Error("Video details request failed");const details=await detailsResponse.json() as {items?:Array<{id:string;contentDetails?:{duration?:string}}>};const seconds=new Map((details.items??[]).map(x=>[x.id,duration(x.contentDetails?.duration??"")]));const videos=entries.map(x=>{const durationSeconds=seconds.get(x.id)??0;return{id:x.id,title:x.title,thumbnail:`https://i.ytimg.com/vi/${x.id}/hqdefault.jpg`,publishedAt:x.publishedAt,durationSeconds,isShort:durationSeconds>0&&durationSeconds<=60,url:`https://www.youtube.com/watch?v=${x.id}`};});res.status(200).json({videos});return;}}
if(channelId){const videos=await rss(channelId);if(videos.length){res.status(200).json({videos});return;}}res.status(200).json({videos:fallbackVideos.filter(isVideoRow)});}catch{try{if(channelId){const videos=await rss(channelId);if(videos.length){res.status(200).json({videos});return;}}}catch{/* Static verified fallback below. */}res.status(200).json({videos:fallbackVideos.filter(isVideoRow)});}}
