-- =============================================================
-- ShuzhFit Beginner Exercise Library seed (24 exercises)
-- Uses INSERT IGNORE so re-running never duplicates (slug unique).
-- =============================================================
USE shuzhfit;

INSERT IGNORE INTO exercises (name, slug, muscles_worked, benefits, form_guide, mistakes, reps) VALUES
('Barbell Bench Press', 'barbell-bench-press', 'Chest, Triceps, Front Delts',
 '<p>The classic upper-body pressing lift. Builds chest strength and muscle, improves pushing power, and supports better posture when done with control.</p>',
 '<p>1) Set eye level just in front of the bar. 2) Plant feet, squeeze shoulder blades down and back. 3) Lower the bar to mid-chest with control. 4) Press up and slightly back without flaring elbows to 90 degrees.</p>',
 '<p>Bouncing the bar off the chest, flaring elbows wide, lifting hips off the bench, and rushing the lowering phase.</p>',
 '3 sets x 6-10 reps'),
('Incline Dumbbell Press', 'incline-dumbbell-press', 'Upper Chest, Front Delts, Triceps',
 '<p>Targets the upper chest and shoulders. Complements flat pressing and helps build a fuller, more balanced chest.</p>',
 '<p>1) Set bench to 30-45 degrees. 2) Start with dumbbells at chest level. 3) Press up and slightly together. 4) Lower with control until elbows are just below the bench line.</p>',
 '<p>Setting the bench too steep (turns it into a shoulder press), clanging dumbbells together, and half reps.</p>',
 '3 sets x 8-12 reps'),
('Push-Up', 'push-up', 'Chest, Triceps, Core',
 '<p>The best zero-equipment pressing exercise. Builds chest, triceps, and core stability at the same time.</p>',
 '<p>1) Hands slightly wider than shoulders. 2) Body forms a straight line from head to heels. 3) Lower until chest is close to the floor. 4) Press up fully without letting hips sag.</p>',
 '<p>Sagging hips, flared elbows at 90 degrees, short range of motion, and craning the neck.</p>',
 '3 sets x 10-20 reps'),
('Overhead Press', 'overhead-press', 'Shoulders, Triceps, Core',
 '<p>Builds strong, round shoulders and real-world overhead strength. Trains the core to stay tight under load.</p>',
 '<p>1) Stand with feet hip-width, bar at collarbone. 2) Brace the core and glutes. 3) Press the bar overhead, moving the head back slightly as it passes. 4) Finish with the bar over the middle of your head.</p>',
 '<p>Leaning back excessively, pressing around the head instead of over it, and using too much leg drive.</p>',
 '3 sets x 6-10 reps'),
('Lateral Raise', 'lateral-raise', 'Side Delts',
 '<p>Isolates the side delts to build shoulder width. Low load, high control — perfect for beginners.</p>',
 '<p>1) Stand tall with light dumbbells at your sides. 2) Raise arms out to shoulder height with a slight elbow bend. 3) Lead with the elbows. 4) Lower slowly.</p>',
 '<p>Swinging the weight, raising above shoulder height with shrugs, and using weights that are too heavy.</p>',
 '3 sets x 12-15 reps'),
('Pull-Up / Assisted Pull-Up', 'pull-up', 'Lats, Biceps, Upper Back',
 '<p>The king of pulling movements. Builds the lats, biceps, and grip while improving posture.</p>',
 '<p>1) Grip slightly wider than shoulders. 2) Start from a dead hang with active shoulders. 3) Pull the chest toward the bar. 4) Lower with control to a full hang.</p>',
 '<p>Kipping unpredictably, half reps, shrugging the shoulders to the ears, and dropping down fast.</p>',
 '3 sets x 4-8 reps'),
('Lat Pulldown', 'lat-pulldown', 'Lats, Biceps, Upper Back',
 '<p>A beginner-friendly way to build the pulling muscles before full pull-ups are possible.</p>',
 '<p>1) Adjust the thigh pad so legs stay planted. 2) Grip wider than shoulders. 3) Pull the bar to your upper chest while keeping the torso mostly upright. 4) Control the bar back up.</p>',
 '<p>Leaning way back, pulling to the stomach, yanking with the arms, and shrugging at the top.</p>',
 '3 sets x 8-12 reps'),
('Seated Cable Row', 'seated-cable-row', 'Mid Back, Lats, Biceps',
 '<p>Builds mid-back thickness and improves posture. Great for balancing out all the pressing beginners do.</p>',
 '<p>1) Sit tall with a slight forward reach. 2) Pull the handle to the lower chest. 3) Squeeze the shoulder blades together. 4) Return with control without letting the torso jerk.</p>',
 '<p>Rocking back and forth, pulling with the biceps only, and shrugging the shoulders.</p>',
 '3 sets x 8-12 reps'),
('Dumbbell Row', 'dumbbell-row', 'Lats, Mid Back, Biceps',
 '<p>A simple unilateral row that builds back strength and fixes side-to-side imbalances.</p>',
 '<p>1) Support one hand on a bench, back flat and close to parallel. 2) Let the dumbbell hang. 3) Row it to your hip. 4) Lower fully without rotating the torso.</p>',
 '<p>Rounding the back, twisting the torso to lift heavier, and doing tiny half reps.</p>',
 '3 sets x 8-12 reps'),
('Barbell Squat', 'barbell-squat', 'Quads, Glutes, Core',
 '<p>The foundation of lower-body strength. Builds the quads, glutes, and full-body stability.</p>',
 '<p>1) Bar on upper traps, feet shoulder-width. 2) Brace the core. 3) Sit down and slightly back until thighs are at least parallel. 4) Drive up through mid-foot.</p>',
 '<p>Knees caving inward, heels lifting, rounding the lower back, and going too heavy too soon.</p>',
 '3 sets x 6-10 reps'),
('Goblet Squat', 'goblet-squat', 'Quads, Glutes, Core',
 '<p>The easiest way to learn squatting pattern with weight. The front-loaded weight keeps the torso upright.</p>',
 '<p>1) Hold a dumbbell or kettlebell at chest height. 2) Feet shoulder-width. 3) Squat between the knees keeping the chest tall. 4) Drive up through the floor.</p>',
 '<p>Letting the weight drift away from the chest, rising onto the toes, and rushing the reps.</p>',
 '3 sets x 10-15 reps'),
('Leg Press', 'leg-press', 'Quads, Glutes, Hamstrings',
 '<p>A guided machine squat that lets beginners load the legs safely while learning control.</p>',
 '<p>1) Feet shoulder-width on the platform. 2) Lower until knees are about 90 degrees. 3) Press back up without locking the knees hard. 4) Keep the lower back on the pad.</p>',
 '<p>Lowering too deep until the lower back rounds, slamming the weight, and locking knees aggressively.</p>',
 '3 sets x 10-15 reps'),
('Romanian Deadlift', 'romanian-deadlift', 'Hamstrings, Glutes, Lower Back',
 '<p>Teaches the hip hinge and builds the hamstrings and glutes while strengthening the lower back.</p>',
 '<p>1) Stand tall holding the bar or dumbbells at the thighs. 2) Push the hips back with a slight knee bend. 3) Lower until you feel a hamstring stretch. 4) Drive the hips forward to stand.</p>',
 '<p>Rounding the back, squatting instead of hinging, and overextending at the top.</p>',
 '3 sets x 8-12 reps'),
('Walking Lunge', 'walking-lunge', 'Quads, Glutes, Hamstrings',
 '<p>Builds single-leg strength, balance, and hip stability. Humble but extremely effective.</p>',
 '<p>1) Step forward into a long stride. 2) Lower the back knee toward the floor. 3) Push through the front heel to stand. 4) Alternate legs as you walk.</p>',
 '<p>Taking short steps, letting the front knee cave in, and slamming the back knee down.</p>',
 '3 sets x 10-12 per leg'),
('Leg Curl', 'leg-curl', 'Hamstrings',
 '<p>Isolates the hamstrings, which support knee health and balance out quad-dominant training.</p>',
 '<p>1) Adjust the pad just above the heels. 2) Curl the weight without lifting the hips. 3) Pause briefly at the top. 4) Lower slowly.</p>',
 '<p>Jerking the weight, lifting the hips off the pad, and rushing the lowering phase.</p>',
 '3 sets x 10-15 reps'),
('Calf Raise', 'calf-raise', 'Calves',
 '<p>Builds calf size and ankle strength. Simple, safe, and easy to progress slowly.</p>',
 '<p>1) Balls of the feet on a step or platform. 2) Lower the heels for a full stretch. 3) Rise as high as possible. 4) Pause at the top briefly.</p>',
 '<p>Bouncing with no control, tiny range of motion, and going too heavy to feel the calves.</p>',
 '3 sets x 12-20 reps'),
('Plank', 'plank', 'Core, Shoulders',
 '<p>Teaches the core to brace properly, which makes every other lift safer and stronger.</p>',
 '<p>1) Elbows under shoulders. 2) Body in a straight line. 3) Squeeze glutes and brace the abs. 4) Breathe steadily while holding.</p>',
 '<p>Hips sagging or piking, holding the breath, and chasing long times with bad form.</p>',
 '3 sets x 20-45 sec'),
('Hanging Knee Raise', 'hanging-knee-raise', 'Abs, Hip Flexors, Grip',
 '<p>Trains the lower abs and grip strength with minimal equipment.</p>',
 '<p>1) Hang from a bar with active shoulders. 2) Raise the knees toward the chest without swinging. 3) Lower slowly. 4) Keep the movement controlled.</p>',
 '<p>Swinging for momentum, arching the back at the bottom, and rushing the reps.</p>',
 '3 sets x 8-12 reps'),
('Barbell Curl', 'barbell-curl', 'Biceps, Forearms',
 '<p>Directly builds the biceps. Simple to learn and easy to progress over time.</p>',
 '<p>1) Stand tall, elbows pinned to the sides. 2) Curl the bar to shoulder height. 3) Squeeze at the top. 4) Lower slowly to full extension.</p>',
 '<p>Swinging the torso, letting the elbows drift forward, and doing half reps.</p>',
 '3 sets x 8-12 reps'),
('Triceps Pushdown', 'triceps-pushdown', 'Triceps',
 '<p>Isolates the triceps safely. Great for beginners to learn what triceps activation feels like.</p>',
 '<p>1) Elbows locked to your sides. 2) Push the handle down until arms are straight. 3) Squeeze the triceps. 4) Return with control.</p>',
 '<p>Flaring the elbows, leaning over the bar to press with body weight, and partial reps.</p>',
 '3 sets x 10-15 reps'),
('Face Pull', 'face-pull', 'Rear Delts, Upper Back',
 '<p>Strengthens the often-neglected rear delts and improves shoulder health for pressers.</p>',
 '<p>1) Set the cable at eye level. 2) Pull the rope toward the face. 3) Split the hands apart beside the ears. 4) Return slowly.</p>',
 '<p>Going too heavy, turning it into a row, and shrugging the shoulders up to the ears.</p>',
 '3 sets x 12-15 reps'),
('Dumbbell Chest Fly', 'dumbbell-chest-fly', 'Chest, Front Delts',
 '<p>Stretches and isolates the chest. A good finisher after presses.</p>',
 '<p>1) Lie flat with light dumbbells above the chest. 2) Lower in a wide arc until you feel a stretch. 3) Bring them back together as if hugging a tree. 4) Keep a slight elbow bend throughout.</p>',
 '<p>Turning it into a press by bending elbows too much, going too heavy, and dropping too deep.</p>',
 '3 sets x 10-15 reps'),
('Glute Bridge', 'glute-bridge', 'Glutes, Hamstrings, Core',
 '<p>Teaches glute activation and protects the lower back. Perfect for beginners and rest days.</p>',
 '<p>1) Lie on your back, knees bent. 2) Drive through the heels. 3) Lift the hips until the body is straight. 4) Squeeze the glutes at the top, then lower slowly.</p>',
 '<p>Overextending the lower back, pushing through the toes, and rushing without squeezing.</p>',
 '3 sets x 12-15 reps'),
('Dead Hang', 'dead-hang', 'Grip, Lats, Shoulders',
 '<p>Builds grip strength and shoulder health while decompressing the spine after heavy lifts.</p>',
 '<p>1) Grip the bar shoulder-width. 2) Hang with arms straight. 3) Keep shoulders slightly active, not fully loose. 4) Breathe and hold.</p>',
 '<p>Fully collapsing the shoulders, holding the breath, and dropping off the bar instead of stepping down.</p>',
 '3 sets x 20-40 sec');

