import { useCallback, useEffect, useState } from "react";
import { upload } from "@vercel/blob/client";
import { Helmet } from "react-helmet-async";

type MediaItem = { id: number; url: string; pathname: string; filename: string; contentType: string; size: number; width: number | null; height: number | null; altText: string };
const accepted = new Set(["image/jpeg", "image/png", "image/webp"]);

export function AdminMediaPage() {
  const [items, setItems] = useState<MediaItem[]>([]); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/media", { credentials: "same-origin" }); if (!response.ok) throw new Error("Unable to load media library."); setItems(await response.json() as MediaItem[]); }, []);
  useEffect(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load media.")); }, [load]);
  async function acceptFiles(files: FileList | File[]) { setError(""); for (const file of Array.from(files)) { if (!accepted.has(file.type) || file.size > 8 * 1024 * 1024) { setError(`${file.name}: choose a JPEG, PNG, or WebP under 8 MB.`); continue; } setBusy(true); setProgress(0); try { await upload(file.name, file, { access: "public", handleUploadUrl: "/api/admin/media", onUploadProgress: (event) => setProgress(Math.round(event.percentage)) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } finally { setBusy(false); setProgress(0); } } }
  async function updateAlt(item: MediaItem, altText: string) { const response = await fetch("/api/admin/media", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "alt", id: item.id, altText }) }); if (!response.ok) setError("Could not update alternative text."); else await load(); }
  async function remove(item: MediaItem) { if (!window.confirm(`Delete ${item.filename}? This also removes the image from Blob storage.`)) return; const response = await fetch("/api/admin/media", { method: "DELETE", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "delete", id: item.id }) }); if (!response.ok) { setError("Could not delete this image."); return; } await load(); }
  return <><Helmet><title>Media · Admin</title></Helmet><section className="pg page"><div className="container admin-stack"><header className="pg-head"><span className="pg-kicker">Admin</span><h1>Media library</h1><p className="pg-intro">Upload and manage site images.</p></header><label className="media-drop" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void acceptFiles(event.dataTransfer.files); }}><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => { if (event.target.files) void acceptFiles(event.target.files); event.target.value = ""; }} /><strong>Drop images here or choose files</strong><span>JPEG, PNG, WebP · up to 8 MB each</span>{busy ? <progress max={100} value={progress}>{progress}%</progress> : null}</label>{error ? <p role="alert">{error}</p> : null}{!items.length ? <div className="empty-state">No images uploaded yet.</div> : <div className="media-grid">{items.map((item) => <article className="app-panel media-card" key={item.id}><img src={item.url} alt={item.altText} width={item.width ?? 640} height={item.height ?? 480} loading="lazy"/><strong>{item.filename}</strong><small>{(item.size / 1024).toFixed(0)} KB · {item.contentType}</small><label className="field"><span>Alternative text</span><input defaultValue={item.altText} onBlur={(event) => { if (event.target.value !== item.altText) void updateAlt(item, event.target.value); }}/></label><div className="btn-row"><button className="btn btn-sm" onClick={() => void navigator.clipboard.writeText(item.url)}>Copy URL</button><button className="btn btn-sm" onClick={() => void remove(item)}>Delete</button></div></article>)}</div>}</div></section></>;
}

export function MediaPicker({ onSelect, onClose }: { onSelect: (item: MediaItem) => void; onClose: () => void }) {
  const [items, setItems] = useState<MediaItem[]>([]);
  useEffect(() => { void fetch("/api/admin/media", { credentials: "same-origin" }).then((response) => response.json()).then((data: unknown) => { if (Array.isArray(data)) setItems(data as MediaItem[]); }); }, []);
  return <div className="modal-backdrop" role="presentation" onClick={onClose}><section className="app-panel media-picker" role="dialog" aria-modal="true" aria-label="Choose media" onClick={(event) => event.stopPropagation()}><div className="meal-day-header"><h2>Choose media</h2><button className="btn" onClick={onClose}>Close</button></div><div className="media-grid">{items.map((item) => <button className="media-picker-item" key={item.id} onClick={() => onSelect(item)}><img src={item.url} alt={item.altText} loading="lazy"/><span>{item.filename}</span></button>)}</div></section></div>;
}
