import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
type Comment = { id: string; author: string; body: string; createdAt: string; itemType: string; itemSlug: string | null };
export function AdminCommentsPage() {
  const [items, setItems] = useState<Comment[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState("");
  const load = () => fetch("/api/admin/comments", { credentials: "same-origin" }).then(async (response) => { if (!response.ok) throw new Error(); setItems(await response.json() as Comment[]); }).catch(() => setError("Unable to load comments."));
  useEffect(() => { void load(); }, []);
  async function remove(ids: string[]) { if (!ids.length || !window.confirm(`Delete ${ids.length} selected comment${ids.length === 1 ? "" : "s"}?`)) return; const bulk = ids.length > 1; const response = await fetch(bulk ? "/api/admin/comments" : `/api/admin/comments?id=${ids[0]}`, { method: "DELETE", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(bulk ? { ids: ids.map(Number) } : {}) }); if (response.ok) { setItems((current) => current.filter((comment) => !ids.includes(comment.id))); setSelected([]); } else setError("Unable to delete the selected comment(s)."); }
  return <><Helmet><title>Comments</title></Helmet><section className="pg page"><div className="container"><div className="pg-head"><span className="pg-kicker">Admin</span><h1>Comments</h1><p className="pg-intro">Review and moderate community comments.</p></div>{error ? <p role="alert">{error}</p> : null}<div className="btn-row"><label><input type="checkbox" checked={items.length > 0 && selected.length === items.length} onChange={(event) => setSelected(event.target.checked ? items.map((item) => item.id) : [])}/> Select all</label><button className="btn btn-sm" disabled={!selected.length} onClick={() => void remove(selected)}>Delete selected ({selected.length})</button></div><div className="message-list">{items.length ? items.map((item) => <article key={item.id} className="admin-panel message-card"><label><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))}/> Select comment</label><div className="admin-item-head"><strong>{item.author}</strong><span>{new Date(item.createdAt).toLocaleDateString()}</span></div><p>{item.itemSlug ? <a href={`/${item.itemType === "exercise" ? "exercises" : "blog"}/${encodeURIComponent(item.itemSlug)}`} target="_blank" rel="noopener noreferrer">{item.itemType}: {item.itemSlug} ↗</a> : item.itemType}</p><p className="message-body">{item.body}</p><button className="btn btn-sm" onClick={() => void remove([item.id])}>Delete</button></article>) : <p className="empty-state">No comments yet.</p>}</div></div></section></>;
}
