import { useCallback, useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";

type Member = { id: string; name: string; email: string; role: "user" | "admin"; goal: string | null; joined: string; lastActive: string | null; workoutsCount: number; onboarded: boolean };
type Detail = { member: Member & { experience?: string; heightCm?: number; ageYears?: number; daysPerWeek?: number; equipment?: string }; sessions: Array<{ id: string; name: string; workoutDate: string; status: string }> };
export function AdminMembersPage() {
  const [members, setMembers] = useState<Member[]>([]); const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [onboarded, setOnboarded] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const params = new URLSearchParams({ page: String(page), q: query, role, onboarded }); const response = await fetch(`/api/admin/members?${params}`, { credentials: "same-origin" }); const body = await response.json() as { members?: Member[]; total?: number; error?: string | { message?: string } }; if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "Unable to load members."); setMembers(body.members ?? []); setTotal(body.total ?? 0); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load members."); } }, [page, query, role, onboarded]);
  useEffect(() => { void load(); }, [load]);
  async function showDetail(member: Member) { const response = await fetch(`/api/admin/members?id=${member.id}`, { credentials: "same-origin" }); if (response.ok) setDetail(await response.json() as Detail); }
  async function changeRole(member: Member) { const role = member.role === "admin" ? "user" : "admin"; const response = await fetch("/api/admin/members", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "role", userId: Number(member.id), role }) }); if (!response.ok) { setError("Could not update this member's role."); return; } await load(); }
  async function deleteMember(member: Member) { const confirmEmail = window.prompt(`Type ${member.email} to permanently delete this member and their data.`); if (confirmEmail === null) return; const response = await fetch("/api/admin/members", { method: "DELETE", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "delete", userId: Number(member.id), confirmEmail }) }); if (!response.ok) { setError("Could not delete this member. Check the confirmation email."); return; } await load(); }
  async function exportCsv() { const params = new URLSearchParams({ export: "csv", q: query, role, onboarded }); const response = await fetch(`/api/admin/members?${params}`, { credentials: "same-origin" }); if (!response.ok) { setError("Could not export member data."); return; } const body = await response.json() as { csv: string }; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([body.csv], { type: "text/csv" })); link.download = "shuzhfit-members.csv"; link.click(); URL.revokeObjectURL(link.href); }
  return <><Helmet><title>Members · Admin</title></Helmet><section className="pg page"><div className="container admin-stack"><header className="pg-head"><span className="pg-kicker">Admin</span><h1>Members</h1></header><div className="admin-toolbar"><label className="field"><span>Search name or email</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /></label><label className="field"><span>Role</span><select value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option><option value="user">Member</option><option value="admin">Admin</option></select></label><label className="field"><span>Onboarding</span><select value={onboarded} onChange={(event) => setOnboarded(event.target.value)}><option value="">All</option><option value="true">Complete</option><option value="false">Incomplete</option></select></label><button className="btn" onClick={() => void exportCsv()}>Export CSV</button></div>{error ? <p role="alert">{error}</p> : null}<div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Joined</th><th>Last active</th><th>Workouts</th><th>Role</th><th>Actions</th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><td><button className="table-link" onClick={() => void showDetail(member)}>{member.name}</button></td><td>{member.email}</td><td>{new Date(member.joined).toLocaleDateString()}</td><td>{member.lastActive ? new Date(member.lastActive).toLocaleDateString() : "—"}</td><td>{member.workoutsCount}</td><td>{member.role}</td><td><button className="btn btn-sm" onClick={() => void changeRole(member)}>{member.role === "admin" ? "Demote" : "Promote"}</button> <button className="btn btn-sm" onClick={() => void deleteMember(member)}>Delete</button></td></tr>)}</tbody></table></div><div className="btn-row"><button className="btn" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} · {total} members</span><button className="btn" disabled={page * 20 >= total} onClick={() => setPage(page + 1)}>Next</button></div></div></section>{detail ? <div className="modal-backdrop" role="presentation" onClick={() => setDetail(null)}><section className="app-panel quick-log-modal" role="dialog" aria-modal="true" aria-labelledby="member-detail-title" onClick={(event) => event.stopPropagation()}><button className="btn" onClick={() => setDetail(null)}>Close</button><h2 id="member-detail-title">{detail.member.name}</h2><p>{detail.member.email} · {detail.member.goal ?? "Goal not set"}</p><p>{detail.member.experience ?? "Experience not set"} · {detail.member.equipment ?? "Equipment not set"}</p><p>{detail.member.workoutsCount} completed workouts</p><h3>Recent sessions</h3>{detail.sessions.map((session) => <p key={session.id}>{session.name} · {new Date(session.workoutDate).toLocaleDateString()}</p>)}</section></div> : null}</>;
}
