import { useCallback, useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
type Message = { id: number; name: string; email: string; message: string; createdAt: string; isRead: boolean };
export function AdminMessagesPage() {
  const [items, setItems] = useState<Message[]>([]); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/admin/messages", { credentials: "same-origin" }); if (!response.ok) throw new Error(); setItems(await response.json() as Message[]); } catch { setError("Unable to load contact messages."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function markRead(item: Message, isRead: boolean) { const response = await fetch("/api/admin/messages", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id, isRead }) }); if (response.ok) setItems((current) => current.map((message) => message.id === item.id ? { ...message, isRead } : message)); else setError("Unable to update message status."); }
  async function remove(id: number) { if (!window.confirm("Delete this message?")) return; const response = await fetch(`/api/admin/messages?id=${id}`, { method: "DELETE", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: "{}" }); if (response.ok) setItems((current) => current.filter((message) => message.id !== id)); else setError("Unable to delete message."); }
  return <><Helmet><title>Messages</title></Helmet><section className="pg page"><div className="container"><div className="pg-head"><span className="pg-kicker">Admin</span><h1>Messages</h1><p className="pg-intro">Contact requests from the community.</p></div>{error && <p role="alert">{error}</p>}<div className="message-list">{items.length ? items.map((item) => <article key={item.id} className={`admin-panel message-card${item.isRead ? "" : " unread"}`}><div className="admin-item-head"><strong>{item.name}</strong><span>{new Date(item.createdAt).toLocaleDateString()} · {item.isRead ? "Read" : "Unread"}</span></div><p>{item.email}</p><p className="message-body">{item.message}</p><div className="btn-row"><button className="btn btn-sm" onClick={() => void markRead(item, !item.isRead)}>{item.isRead ? "Mark unread" : "Mark read"}</button><a className="btn btn-sm" href={`mailto:${encodeURIComponent(item.email)}?subject=${encodeURIComponent("Re: ShuzhFit enquiry")}`}>Reply by email</a><button className="btn btn-sm" onClick={() => void remove(item.id)}>Delete</button></div></article>) : <p className="empty-state">No messages yet.</p>}</div></div></section></>;
}
