import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { calculateFitnessMetrics } from "../../shared/fitness";

type Food={id:number;name:string;calories:number;proteinG:number;carbsG:number;fatG:number;mealType:string}; type FoodValue=Omit<Food,"id"|"mealType"> & {mealType?:string;estimate?:boolean}; type Data={foods:Food[];water:number;savedFoods:FoodValue[];commonFoods:FoodValue[];weeklyCalories:Array<{date:string;calories:number}>;profile:null|{sex:"male"|"female"|"other";ageYears:number;heightCm:number;weightKg:number;activityLevel:number;goal:"fat_loss"|"maintain"|"muscle_gain"}};
const today=()=>new Date().toISOString().slice(0,10);
export function NutritionLogPage(){
 const [date,setDate]=useState(today()),[data,setData]=useState<Data|null>(null),[name,setName]=useState(""),[calories,setCalories]=useState(0),[proteinG,setProtein]=useState(0),[carbsG,setCarbs]=useState(0),[fatG,setFat]=useState(0),[mealType,setMealType]=useState("breakfast"),[message,setMessage]=useState("");
 const load=()=>fetch(`/api/nutrition?date=${date}`,{credentials:"include"}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x?.error?.message??"Could not load nutrition");setData(x as Data)}).catch(e=>setMessage(e instanceof Error?e.message:"Could not load nutrition"));useEffect(()=>{void load()},[date]);
 const totals=useMemo(()=>data?.foods.reduce((a,f)=>({calories:a.calories+f.calories,protein:a.protein+f.proteinG,carbs:a.carbs+f.carbsG,fat:a.fat+f.fatG}),{calories:0,protein:0,carbs:0,fat:0})??{calories:0,protein:0,carbs:0,fat:0},[data]);
 const target=data?.profile?calculateFitnessMetrics({...data.profile,goal:data.profile.goal}):null;
 async function add(food?:FoodValue){const entry=food??{name,calories,proteinG,carbsG,fatG,mealType};const r=await fetch("/api/nutrition",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...entry,date,mealType})});if(!r.ok){setMessage("Could not save this food.");return;}setName("");setMessage("Food added.");await load()}
 async function remove(id:number){await fetch(`/api/nutrition?id=${id}`,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json"},body:"{}"});await load()}
 async function waterChange(delta:number){const glasses=Math.max(0,(data?.water??0)+delta);await fetch("/api/nutrition",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,glasses})});await load()}
 const macroBars=[{label:"Protein",amount:totals.protein,target:target?.proteinTargetG??0,color:"#f47735"},{label:"Carbs",amount:totals.carbs,target:(target?.calorieTarget??0)*.45/4,color:"#5db5ef"},{label:"Fat",amount:totals.fat,target:(target?.calorieTarget??0)*.25/9,color:"#bb89f5"}];
 return <><Helmet><title>Nutrition Log</title></Helmet><section className="pg page"><div className="container" style={{display:"grid",gap:22}}><div className="pg-head"><span className="pg-kicker">Fuel</span><h1>Nutrition log</h1><p className="pg-intro">Track meals, macros, and hydration for each day.</p></div>
 <div className="app-panel nutrition-dashboard"><div className="meal-day-header"><button className="btn btn-secondary" onClick={()=>setDate(d=>{const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()-1);return x.toISOString().slice(0,10)})}>Previous day</button><label className="field"><span>Day</span><input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><button className="btn btn-secondary" disabled={date>=today()} onClick={()=>setDate(d=>{const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+1);return x.toISOString().slice(0,10)})}>Next day</button></div>
 <div className="nutrition-overview"><div className="calorie-ring" style={{"--ring-progress":`${Math.min(100,totals.calories/(target?.calorieTarget||1)*100)}%`} as React.CSSProperties}><strong>{totals.calories}</strong><span>of {target?.calorieTarget??"—"} kcal</span></div><div className="macro-bars">{macroBars.map(m=><div key={m.label}><div className="meal-day-header"><b>{m.label}</b><span>{Math.round(m.amount)} / {Math.round(m.target)} g</span></div><progress max={Math.max(m.target,1)} value={Math.min(m.amount,m.target)} style={{accentColor:m.color}}/></div>)}</div></div>
 <h2>Meals</h2><div className="field-grid is-two-col"><label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Food or meal"/></label><label className="field"><span>Meal</span><select value={mealType} onChange={e=>setMealType(e.target.value)}><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option><option value="snack">Snack</option></select></label></div><div className="field-grid is-four-col">{[["Calories",calories,setCalories],["Protein (g)",proteinG,setProtein],["Carbs (g)",carbsG,setCarbs],["Fat (g)",fatG,setFat]].map(([label,val,set])=><label className="field" key={String(label)}><span>{String(label)}</span><input type="number" min="0" value={Number(val)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}</div><button className="btn btn-primary" onClick={()=>void add()} disabled={!name.trim()}>Add food</button>{message&&<p role="status">{message}</p>}
 {["breakfast","lunch","dinner","snack"].map(meal=><section className="meal-section" key={meal}><h3>{meal[0]?.toUpperCase()}{meal.slice(1)}</h3>{data?.foods.filter(f=>f.mealType===meal).map(f=><div className="session-item meal-row" key={f.id}><div><b>{f.name}</b><p>{f.calories} kcal · {f.proteinG}P / {f.carbsG}C / {f.fatG}F</p></div><button className="btn btn-ghost" onClick={()=>void remove(f.id)} aria-label={`Delete ${f.name}`}>Delete</button></div>)}</section>)}
 <h2>Quick add</h2><div className="food-chips">{data?.savedFoods.map(f=><button key={`s-${f.name}`} className="btn btn-secondary" onClick={()=>void add(f)}>{f.name} · {f.calories} kcal</button>)}{data?.commonFoods.map(f=><button key={`c-${f.name}`} className="btn btn-ghost" onClick={()=>void add({...f,mealType})}>{f.name} · {f.calories} kcal{f.estimate?"*":""}</button>)}</div><small>*Estimated per serving.</small>
 <div className="meal-day-header"><h2>Water</h2><div className="btn-row"><button className="btn btn-secondary" onClick={()=>void waterChange(-1)}>− Glass</button><strong>{data?.water??0} glasses</strong><button className="btn btn-secondary" onClick={()=>void waterChange(1)}>+ Glass</button></div></div>
 <h2>Last 7 days · calories</h2><div className="weekly-calories">{data?.weeklyCalories.map(day=><div key={day.date}><div className="weekly-calorie-bar" style={{height:`${Math.max(4,Math.min(100,day.calories/(target?.calorieTarget||2000)*100))}%`}} title={`${day.calories} kcal`}/><small>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined,{weekday:"short"})}</small><b>{day.calories}</b></div>)}</div>
 </div></div></section></>;
}
