import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
type Entry={id:number;date:string;weightKg:number|null;waistCm:number|null;bodyFatPct:number|null;notes:string};type Data={entries:Entry[];goalWeightKg:number;weeklyConsistency:Array<{week:string;count:number}>;personalRecords:Array<{exerciseName:string;estimated1Rm:number}>};
const today=()=>new Date().toISOString().slice(0,10);
export function ProgressPage(){const [data,setData]=useState<Data|null>(null),[date,setDate]=useState(today()),[weight,setWeight]=useState(""),[waist,setWaist]=useState(""),[fat,setFat]=useState(""),[notes,setNotes]=useState(""),[editing,setEditing]=useState<number|null>(null),[message,setMessage]=useState("");const load=()=>fetch("/api/progress",{credentials:"include"}).then(async r=>{const b=await r.json();if(!r.ok)throw Error("Unable to load progress.");setData(b as Data)}).catch(()=>setMessage("Unable to load progress."));useEffect(()=>{void load()},[]);const points=data?.entries.filter(e=>e.weightKg!==null)??[];const values=points.map(p=>p.weightKg as number);const min=Math.min(...values,data?.goalWeightKg||Infinity)-1,max=Math.max(...values,data?.goalWeightKg||0)+1;const point=(v:number,i:number)=>`${40+(points.length<2?0:i*520/(points.length-1))},${160-(v-min)/(max-min||1)*125}`;
 async function save(event:React.FormEvent){event.preventDefault();const body={id:editing??undefined,date,weightKg:weight?Number(weight):null,waistCm:waist?Number(waist):null,bodyFatPct:fat?Number(fat):null,notes};const r=await fetch("/api/progress",{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setMessage("Could not save measurement.");return;}setMessage("Measurement saved.");setEditing(null);setWeight("");setWaist("");setFat("");setNotes("");await load()}
 function edit(e:Entry){setEditing(e.id);setDate(e.date);setWeight(e.weightKg?.toString()??"");setWaist(e.waistCm?.toString()??"");setFat(e.bodyFatPct?.toString()??"");setNotes(e.notes)}
 async function remove(id:number){await fetch(`/api/progress?id=${id}`,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json"},body:"{}"});await load()}
 return <><Helmet><title>Progress</title></Helmet><section className="pg page"><div className="container" style={{display:"grid",gap:22}}><div className="pg-head"><span className="pg-kicker">Results</span><h1>Progress tracking</h1><p className="pg-intro">Measurements, training consistency, and personal records from your account.</p></div>
 <div className="workout-layout"><form onSubmit={save} className="app-panel field-stack"><h2>{editing?"Edit measurement":"Log measurement"}</h2><label className="field"><span>Date</span><input type="date" max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Weight (kg)</span><input type="number" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="field"><span>Waist (cm)</span><input type="number" step="0.1" value={waist} onChange={e=>setWaist(e.target.value)}/></label><label className="field"><span>Body fat (%)</span><input type="number" step="0.1" value={fat} onChange={e=>setFat(e.target.value)}/></label><label className="field"><span>Notes</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{message&&<p role="status">{message}</p>}<button className="btn btn-primary">{editing?"Update measurement":"Save measurement"}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>setEditing(null)}>Cancel edit</button>}</form>
 <div className="app-panel"><h2>Weight trend</h2>{points.length>0?<svg viewBox="0 0 600 190" role="img" aria-label="Weight trend chart" className="progress-chart"><line x1="40" x2="560" y1="160" y2="160"/><line x1="40" x2="40" y1="25" y2="160"/><text x="2" y="35">{Math.ceil(max)} kg</text><text x="2" y="155">{Math.floor(min)} kg</text><text x="40" y="184">{points[0]?.date}</text><text x="500" y="184">{points[points.length-1]?.date}</text>{data?.goalWeightKg? <><line x1="40" x2="560" y1={160-(data.goalWeightKg-min)/(max-min||1)*125} y2={160-(data.goalWeightKg-min)/(max-min||1)*125} className="goal-line"/><text x="45" y="18">Goal {data.goalWeightKg} kg</text></>:null}<polyline points={points.map((p,i)=>point(p.weightKg as number,i)).join(" ")}/>{points.map((p,i)=><circle key={p.id} cx={40+(points.length<2?0:i*520/(points.length-1))} cy={160-((p.weightKg as number)-min)/(max-min||1)*125} r="4"><title>{p.date}: {p.weightKg} kg</title></circle>)}</svg>:<p className="empty-state">Log your first weight to see the trend.</p>}
 <h2>Weekly consistency · last 8 weeks</h2><div className="consistency-bars">{data?.weeklyConsistency.map(w=><div key={w.week}><div className="consistency-bar" style={{height:`${Math.min(100,w.count/Math.max(1, data?.weeklyConsistency.reduce((m,x)=>Math.max(m,x.count),0)??1)*100)}%`}} title={`${w.count} active days`}/><small>{new Date(`${w.week}T12:00:00`).toLocaleDateString(undefined,{month:"numeric",day:"numeric"})}</small><b>{w.count}</b></div>)}</div></div></div>
 <div className="app-panel"><h2>Measurements</h2>{data?.entries.length?data.entries.slice().reverse().map(e=><div className="history-item" key={e.id}><div><strong>{e.date}</strong><p>{e.weightKg??"—"} kg · {e.waistCm??"—"} cm waist · {e.bodyFatPct??"—"}% fat</p>{e.notes&&<small>{e.notes}</small>}</div><div className="btn-row"><button className="btn btn-secondary" onClick={()=>edit(e)}>Edit</button><button className="btn btn-ghost" onClick={()=>void remove(e.id)}>Delete</button></div></div>):<p className="empty-state">No measurements yet.</p>}<h2>Personal records · estimated 1RM</h2>{data?.personalRecords.map(r=><p key={r.exerciseName}><strong>{r.exerciseName}</strong> · {r.estimated1Rm} kg</p>)}</div>
 </div></section></>}
