import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { requireAuth, requireJson, requireOrigin, parseBody, sendError, type ApiRequest, type ApiResponse } from "./_lib/http";

const value = (input: string | string[] | undefined) => Array.isArray(input) ? input[0] : input;
const profileSchema = z.object({ name: z.string().trim().min(1).max(120), goalType: z.enum(["fat_loss","maintain","muscle_gain"]), sex: z.enum(["male","female","other"]), heightCm: z.number().int().min(100).max(250), ageYears: z.number().int().min(13).max(120), experience: z.enum(["beginner","intermediate","advanced"]), daysPerWeek: z.number().int().min(2).max(6), equipment: z.enum(["gym","home_dumbbells","bodyweight"]), activityLevel: z.number().min(1).max(2.5), targetWeightKg: z.number().min(20).max(500), weeklyWorkoutTarget: z.number().int().min(1).max(7) });
const goalSchema = z.object({ title: z.string().trim().min(1).max(200), metric: z.enum(["weight","exercise_weight","workouts_per_week"]), targetValue: z.number().positive(), exerciseName: z.string().max(200).optional(), deadline: z.string().date().optional() });
export default async function handler(req: ApiRequest, res: ApiResponse): Promise<void> {
  if (!["GET","PATCH","POST","DELETE"].includes(req.method ?? "")) { sendError(res,405,"METHOD_NOT_ALLOWED","Method not allowed."); return; }
  if(req.method!=="GET"&&(!requireOrigin(req,res)||!requireJson(req,res))) return;
  const auth=await requireAuth(req,res); if(!auth)return; const userId=Number(auth.id);
  try {
    const [{db},s]=await Promise.all([import("../db"),import("../db/schema")]);
    if(req.method==="GET") {
      const [user,goals,progress,workouts,quick,sets,foods]=await Promise.all([
        db.select().from(s.users).where(eq(s.users.id,userId)).limit(1),
        db.select().from(s.userGoals).where(eq(s.userGoals.userId,userId)).orderBy(desc(s.userGoals.createdAt)),
        db.select().from(s.progressEntries).where(eq(s.progressEntries.userId,userId)).orderBy(desc(s.progressEntries.date)),
        db.select({id:s.workouts.id,date:s.workouts.workoutDate,status:s.workouts.status}).from(s.workouts).where(eq(s.workouts.userId,userId)),
        db.select({date:s.workoutLogs.logDate}).from(s.workoutLogs).where(eq(s.workoutLogs.userId,userId)),
        db.select({exerciseName:s.workoutSets.exerciseName,weightKg:s.workoutSets.weightKg,reps:s.workoutSets.reps,isWarmup:s.workoutSets.isWarmup}).from(s.workoutSets).innerJoin(s.workouts,eq(s.workoutSets.workoutId,s.workouts.id)).where(and(eq(s.workoutSets.userId,userId),eq(s.workouts.status,"finished"))),
        db.select({date:s.foodLogs.logDate}).from(s.foodLogs).where(eq(s.foodLogs.userId,userId)),
      ]);
      const u=user[0]; if(!u){sendError(res,404,"PROFILE_NOT_FOUND","Profile not found.");return;}
      const activeWorkouts=workouts.filter(w=>w.status==="finished"); const activityDates=new Set([...activeWorkouts.map(w=>w.date.toISOString().slice(0,10)),...quick.map(w=>w.date.toISOString().slice(0,10))]); const distinctExercises=new Set(sets.filter(x=>!x.isWarmup).map(x=>x.exerciseName)); const totalVolume=sets.filter(x=>!x.isWarmup).reduce((sum,x)=>sum+Number(x.weightKg??0)*x.reps,0); const foodDates=new Set(foods.map(x=>x.date.toISOString().slice(0,10)));
      const achievements=[{id:"first_session",title:"First session",earned:activeWorkouts.length+quick.length>=1},{id:"three_day_streak",title:"3-day streak",earned:hasStreak(activityDates,3)},{id:"seven_day_streak",title:"7-day streak",earned:hasStreak(activityDates,7)},{id:"ten_sessions",title:"10 sessions",earned:activeWorkouts.length+quick.length>=10},{id:"twenty_five_sessions",title:"25 sessions",earned:activeWorkouts.length+quick.length>=25},{id:"first_lift",title:"First lift logged",earned:sets.some(x=>!x.isWarmup)},{id:"five_exercises",title:"5 different exercises",earned:distinctExercises.size>=5},{id:"ten_thousand_volume",title:"10,000 kg volume",earned:totalVolume>=10000},{id:"food_three_days",title:"Food logged on 3 days",earned:foodDates.size>=3}];
      res.status(200).json({profile:{name:u.name,email:u.email,goalType:u.goalType??"maintain",sex:u.sex??"other",heightCm:u.heightCm??170,ageYears:u.ageYears??30,experience:u.experience??"beginner",daysPerWeek:u.daysPerWeek??3,equipment:u.equipment??"gym",activityLevel:Number(u.activityLevel??1.55),targetWeightKg:Number(u.targetWeightKg??0),weeklyWorkoutTarget:u.weeklyWorkoutTarget},goals:goals.map(g=>({id:g.id,title:g.title,metric:g.metric,targetValue:Number(g.targetValue??0),exerciseName:g.exerciseName,status:g.status,deadline:g.deadline?.toISOString().slice(0,10)??null,currentValue:currentMetric(g.metric,progress,activeWorkouts,sets,g.exerciseName)})),achievements});return;
    }
    if(req.method==="PATCH"&&value(req.query?.action)==="goal") { const id=Number(value(req.query?.id)); const body=parseBody(z.object({status:z.enum(["achieved","active"])}),req.body);if(!body||!Number.isSafeInteger(id)){sendError(res,400,"INVALID_INPUT","Choose a valid goal status.");return;}await db.update(s.userGoals).set({status:body.status,isAchieved:body.status==="achieved",achievedAt:body.status==="achieved"?new Date():null}).where(and(eq(s.userGoals.id,id),eq(s.userGoals.userId,userId)));res.status(200).json({success:true});return; }
    if(req.method==="DELETE"&&value(req.query?.type)==="goal") { const id=Number(value(req.query?.id));if(!Number.isSafeInteger(id)){sendError(res,400,"INVALID_ID","Choose a valid goal.");return;}await db.delete(s.userGoals).where(and(eq(s.userGoals.id,id),eq(s.userGoals.userId,userId)));res.status(200).json({success:true});return; }
    if(req.method==="POST") { const body=parseBody(goalSchema,req.body);if(!body){sendError(res,400,"INVALID_INPUT","Enter a valid goal.");return;}await db.insert(s.userGoals).values({userId,title:body.title,metric:body.metric,targetValue:String(body.targetValue),exerciseName:body.exerciseName??null,deadline:body.deadline?new Date(`${body.deadline}T00:00:00Z`):null});res.status(201).json({success:true});return; }
    const body=parseBody(profileSchema,req.body);if(!body){sendError(res,400,"INVALID_INPUT","Check your profile details.");return;}await db.update(s.users).set({name:body.name,goalType:body.goalType,sex:body.sex,heightCm:body.heightCm,ageYears:body.ageYears,experience:body.experience,daysPerWeek:body.daysPerWeek,equipment:body.equipment,equipmentPreference:body.equipment,activityLevel:String(body.activityLevel),targetWeightKg:String(body.targetWeightKg),weeklyWorkoutTarget:body.weeklyWorkoutTarget}).where(eq(s.users.id,userId));res.status(200).json({success:true});
  } catch { sendError(res,500,"PROFILE_FAILED","Unable to load or save profile data."); }
}
function hasStreak(dates:Set<string>,length:number):boolean { const day=new Date();day.setUTCHours(0,0,0,0);let count=0;for(let i=0;i<366;i++){const key=day.toISOString().slice(0,10);if(!dates.has(key)){if(i===0){day.setUTCDate(day.getUTCDate()-1);continue;}break;}count++;if(count>=length)return true;day.setUTCDate(day.getUTCDate()-1);}return false; }
function currentMetric(metric:string,progress:Array<{weightKg:string|null}>,workouts:Array<{date:Date}>,sets:Array<{exerciseName:string;weightKg:string|null;reps:number;isWarmup:boolean}>,exerciseName:string|null):number { if(metric==="weight")return Number(progress.find(p=>p.weightKg)?.weightKg??0);if(metric==="workouts_per_week"){const since=new Date();since.setUTCDate(since.getUTCDate()-7);return workouts.filter(w=>w.date>=since).length;}return Math.max(0,...sets.filter(s=>!s.isWarmup&&(!exerciseName||s.exerciseName===exerciseName)).map(s=>Number(s.weightKg??0))); }
